# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

pod "Masonry"
pod 'AFNetworking','~>4.0.1'
pod 'YYModel', '~> 1.0.4'
pod 'SVProgressHUD'
pod 'AMap3DMap-NO-IDFA', '~> 8.0.0'
pod 'AMapSearch-NO-IDFA'

target 'MAMapKit-3D-Demo-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAMapKit-3D-Demo-swift

end

target 'MAMapKit_3D_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAMapKit_3D_Demo

end
